"""Sync GitHub repos tagged `featured` into src/data/featuredProjects.ts.

Replaces the hand-authored .md mirrors as the source of truth for the Projects
section. A repo appears only while it carries the `featured` topic on GitHub;
remove the topic and it drops off on the next sync. Each repo's cover image is
its GitHub social-preview (og:image) URL, read from the repo's HTML page so a
custom "Social preview" set in repo settings is used automatically.

The output file is committed to the repo so the static build always has data;
the weekly workflow simply rewrites it in place.
"""

import json
import os
import re
import requests

GITHUB_USER = "Foysal-Munsy"
OUTPUT = "src/data/featuredProjects.ts"


def fetch_cover(full_name: str, session: requests.Session) -> str:
    """Read the repo page's og:image (its social preview) URL."""
    try:
        resp = session.get(f"https://github.com/{full_name}", timeout=15)
        resp.raise_for_status()
        match = re.search(r'property="og:image" content="([^"]+)"', resp.text)
        return match.group(1) if match else ""
    except requests.RequestException:
        return ""


def main() -> None:
    print(f"Fetching repositories for {GITHUB_USER}...")
    url = f"https://api.github.com/users/{GITHUB_USER}/repos?per_page=100&sort=updated"

    headers = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"token {token}"

    session = requests.Session()
    response = session.get(url, headers=headers, timeout=20)
    if response.status_code != 200:
        print(f"Failed to fetch repos: {response.status_code}")
        raise SystemExit(1)
    repos = response.json()

    featured = [r for r in repos if "featured" in (r.get("topics") or [])]
    featured.sort(key=lambda r: r.get("pushed_at") or "", reverse=True)

    projects = []
    for repo in featured:
        name = repo["name"]
        entry = {
            "title": name,
            "repoUrl": repo["html_url"],
            "summary": (repo.get("description") or "").strip(),
            "topics": [t for t in (repo.get("topics") or []) if t != "featured"],
            "cover": fetch_cover(repo["full_name"], session),
            "pushedAt": repo.get("pushed_at") or "",
        }
        if repo.get("homepage"):
            entry["homepage"] = repo["homepage"]
        projects.append(entry)
        print(f"  {name}: cover={bool(entry['cover'])}")

    # json.dumps emits valid TS double-quoted string literals for the plain
    # text GitHub returns (quotes/newlines are escaped), so we can inline it.
    body = [
        "// AUTO-GENERATED by .github/scripts/fetch_github.py - do not edit by hand.",
        "// The Projects shown are exactly the GitHub repos tagged `featured`.",
        "export interface FeaturedRepo {",
        "  title: string;",
        "  repoUrl: string;",
        "  homepage?: string;",
        "  summary: string;",
        "  topics: string[];",
        "  cover: string;",
        "  pushedAt: string;",
        "}",
        "",
        "export const featuredProjects: FeaturedRepo[] = "
        + json.dumps(projects, indent=2)
        + ";",
        "",
    ]
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(body))

    print(f"Wrote {len(projects)} featured repo(s) to {OUTPUT}.")


if __name__ == "__main__":
    main()
