// AUTO-GENERATED by .github/scripts/fetch_github.py - do not edit by hand.
// The Projects shown are exactly the GitHub repos tagged `featured`.
export interface FeaturedRepo {
  title: string;
  repoUrl: string;
  homepage?: string;
  summary: string;
  topics: string[];
  cover: string;
  pushedAt: string;
}

export const featuredProjects: FeaturedRepo[] = [
  {
    "title": "LMS",
    "repoUrl": "https://github.com/Foysal-Munsy/LMS",
    "summary": "A LMS built with a focus on security, scalability, and modern design. It features strict 4-tier Role-Based Access Control (RBAC) enforced on the backend, structured course enrollments, persistent progress tracking, server-side graded quizzes, and a fully functional draft-to-publish blog system.",
    "topics": [
      "nextjs",
      "postgresql",
      "railway",
      "strapi",
      "typescript",
      "vercel"
    ],
    "cover": "https://repository-images.githubusercontent.com/1347611430/907ec9e1-e6ad-46ed-83a2-5e8968f055f4",
    "pushedAt": ""
  }
];
